amazonProperties:
  endpointUrl: 
  accessKey: 
  secretKey: 
  bucketName: elearning-file-warehouse
 
spring:
    servlet:
        multipart:
            max-file-size: 9999999999
            max-request-size: 9999999999
     